### ISSUE TITLE
[jsoo] slide 9 missing closed curly brace

### ISSUE THREAD

**Issue by voiceofrae** [pamelafox/teaching-materials#128]
On the Optional Arguments slide, 

var book = new Book({
    title: "Robot Dreams",
    author: "Isaac Asimov",
    numPages: 320);

is missing the closed curly brace. It should be:

var book = new Book({
    title: "Robot Dreams",
    author: "Isaac Asimov",
    numPages: 320});

**Comment by brendajin** [comment]
@voiceofrae Thanks for catching that! Just fixed it with [23c0a55645b135e5ac5c74d8d5248687f5080a0a](https://github.com/pamelafox/teaching-materials/commit/23c0a55645b135e5ac5c74d8d5248687f5080a0a)

**Comment by voiceofrae** [comment]
Pamela, thanks for catching that - I apologize for not competing the update
before!

On Sat, Aug 8, 2015 at 2:43 PM, Brenda Jin <notifications@github.com> wrote:

> @voiceofrae <https://github.com/voiceofrae> Thanks for catching that!
> Just fixed it with 23c0a55645b135e5ac5c74d8d5248687f5080a0a
> <https://github.com/pamelafox/teaching-materials/commit/23c0a55645b135e5ac5c74d8d5248687f5080a0a>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pamelafox/teaching-materials/issues/128#issuecomment-129048291>
> .
>



-- 

*Renée CS*

Good education is not what fills your head with facts but what stimulates
curiosity. You then learn for the rest of your life. - Neil DeGrasse Tyson
