### ISSUE TITLE
[JS 102] Fixes to slides

### ISSUE THREAD

**Issue by pamelafox** [pamelafox/teaching-materials#134]
Fix the spacing in ){  in all places
Arrays:
- Change push[] to push()
- Change cb to better variable name
- Add a slide before iteration that reviews for loops
- Change the array iteration slide to actually output array contents

Objects:
- Move slide 19 earlier, in first objects part, after variables
- Change year to "year"
- Put "small" in quotes

Functions:
- Change bonus from insult generator to lookupUser function that finds an animal by username
- Fix the typos in arguments slides

Scope:
- Change to secrets and candies

General: prefer using string concatenation in console.log() instead of commas so its easier for them to change/turn into a function (like zoo[key] slide)

**Comment by pamelafox** [comment]
Also, submit to this repo.

**Comment by Yonet** [comment]
All the changes added and pushed.
